export const AUTH_FULFILLED = Symbol("AUTH_FULFILLED");
export const AUTH_REJECT = Symbol("AUTH_REJECT");

export const LOGOUT_FULFILLED = Symbol("LOGOUT_FULFILLED");

export const RECIEVE_AUTH_FULFILLED = Symbol("RECIEVE_AUTH_FULFILLED");
export const RECIEVE_AUTH_REJECT = Symbol("RECIEVE_AUTH_REJECT");

export const REDIRECT = Symbol("REDIRECT");

export const FETCH_MY_CHATS_REQUEST = Symbol("FETCH_MY_CHATS");
export const FETCH_MY_CHATS_FULFILLED = Symbol("FETCH_MY_CHATS");
export const FETCH_MY_CHATS_REJECT = Symbol("FETCH_MY_CHATS");

export const FETCH_ALL_CHATS_REQUEST = Symbol("FETCH_ALL_CHATS_REQUEST");
export const FETCH_ALL_CHATS_FULFILLED = Symbol("FETCH_ALL_CHATS_FULFILLED");
export const FETCH_ALL_CHATS_REJECT = Symbol("FETCH_ALL_CHATS_REJECT");

export const SET_ACTIVE_CHAT = Symbol("SET_ACTIVE_CHAT");
export const UNSET_ACTIVE_CHAT = Symbol("UNSET_ACTIVE_CHAT");

export const FETCH_CHAT_REQUEST = Symbol("FETCH_CHAT_REQUEST");
export const FETCH_CHAT_FULFILLED = Symbol("FETCH_CHAT_FULFILLED");
export const FETCH_CHAT_REJECT = Symbol("FETCH_CHAT_REJECT");

export const JOIN_CHAT_REQUEST = Symbol("JOIN_CHAT_REQUEST")
export const JOIN_CHAT_FULFILLED = Symbol("JOIN_CHAT_FULFILLED")
export const JOIN_CHAT_REJECT = Symbol("JOIN_CHAT_REJECT")

export const LEAVE_CHAT_REQUEST = Symbol("LEAVE_CHAT_REQUEST")
export const LEAVE_CHAT_FULFILLED = Symbol("LEAVE_CHAT_FULFILLED")
export const LEAVE_CHAT_REJECT = Symbol("LEAVE_CHAT_REJECT")

export const DELETE_CHAT_REQUEST = Symbol("DELETE_CHAT_REQUEST")
export const DELETE_CHAT_FULFILLED = Symbol("DELETE_CHAT_FULFILLED")
export const DELETE_CHAT_REJECT = Symbol("DELETE_CHAT_REJECT")

export const CREATE_CHAT_REQUEST = Symbol("CREATE_CHAT_REQUEST")
export const CREATE_CHAT_FULFILLED = Symbol("CREATE_CHAT_FULFILLED")
export const CREATE_CHAT_REJECT = Symbol("CREATE_CHAT_REJECT")

export const SOCKETS_CONNECTION_REQUEST= Symbol('SOCKET_CONNECTION_REQUEST')
export const SOCKETS_CONNECTION_SUCCESS = Symbol('SOCKET_CONNECTION_FULFILLED')
export const SOCKETS_CONNECTION_FAILURE = Symbol('SOCKET_CONNECTION_REJECT')

export const SOCKET_MISSING_CONNECTION= Symbol('SOCKET_MISSING_CONNECTION')

export const MOUNT_CHAT =  Symbol('MOUNT_CHAT')
export const UNMOUNT_CHAT = Symbol('UNMOUNT_CHAT')

export const SEND_MESSAGE =  Symbol('SEND_MESSAGE')
export const RECIEVE_MESSAGE = Symbol('RECIEVE_MESSAGE')
export const RECIEVE_NEW_CHAT =  Symbol('RECIEVE_NEW_CHAT')
export const RECIEVE_DELETED_CHAT = Symbol('RECIEVE_DELETED_CHAT')